locale: "en-GB"
title: "Antfie"
description: "Anthony Fielding"

# https://github.com/mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@4.18.1"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
subtitle: "Anthony Fielding"
name: "Anthony Fielding"
url: "antfie.com"
witter:
  username: "antfie"
author:
  name     : "Anthony Fielding"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Security consultant"
  location : "Manchester, UK" 
