locale: "en-GB"
title: "Antfie"
description: "Anthony Fielding"

# https://github.com/mmistakes/minimal-mistakes
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
remote_theme: "antfie/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
minimal_mistakes_skin: "dark"
subtitle: "Anthony Fielding"
name: "Anthony Fielding"
url: "antfie.com"
include: ["_pages"]
#logo: "/assets/images/avatar.svg"
twitter:
  username: "antfie"
author:
  name     : "Anthony Fielding"
  avatar   : "/assets/images/avatar.svg"
  bio      : "Security consultant"
  location : "Manchester, UK"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/antfie"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/antfie"
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/antfie"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/antfie"
timezone: "Europe/London"
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
 # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
