locale: "en-GB"
title: "Antfie"
subtitle: "Anthony Fielding"
description: "Anthony Fielding"

# https://github.com/mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@4.18.1"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
